### ISSUE TITLE
Browser issue: Search box sizing on IE9

### ISSUE THREAD

**Issue by dajoturner** [ucsc/webtemplates2014#258]
John Lallemand wrote: "Campus home: In IE9, the search box has its text cutoff on the bottom on the People, Calendar and A-Z pages."
See: http://www-dev.ucsc.edu/tools/people.html

In Chrome:
![image](https://cloud.githubusercontent.com/assets/8182013/4015335/be83f8cc-2a29-11e4-9f42-14cf7fc0ea03.png)

In IE9:
![image](https://cloud.githubusercontent.com/assets/8182013/4015343/cce36ba0-2a29-11e4-90ee-2cbb70d1d101.png)

**Comment by knice** [comment]
I've converted the `font-size` and `padding` on the search box to whole numbers instead of fractions of pixels (what was `14.5567px` is now `15px`). The IE9 search box size is still shorter than other browsers, but the text no longer looks cut off. Also, IE9 accounts for less than 1% of visits to ucsc.edu, so we can assume this fix is *good enough* for IE9 users.

![screen shot 2015-05-28 at 8 37 26 am](https://cloud.githubusercontent.com/assets/36719/7866559/267ffddc-0525-11e5-8ccd-23946686142a.png)
