### ISSUE TITLE
News index page headings & structure accessibility issue

### ISSUE THREAD

**Issue by dajoturner** [ucsc/webtemplates2014#267]
Len Burns reported this issue. It sounds like an annoyance to users, but I think the volume is pretty low, so I'm setting this to Could Wait.

I'm assigning to T for the user-facing advice at the bottom. @teresasilva71 T, please track that as Help content or good advice for Directory users, then leave this assigned to no one.

http://admissions-dev.ucsc.edu/news-events/news/index.html

Anchors the level 3 headings for each story in the title.  This means that
if one wishes to know the date and name, one must use the arrow keys to move
upward, and then move back down to activate the link.  Because the date is
an important piece of information, it would be better were it included when
the level 3 heading is read.

Also, I did not initially realize that the name to the left of the title is
a small photograph.  For this alt text, I would suggest adding the words:
“Photo of” so users realize this is more than a link.

**Comment by knice** [comment]
This one is kind of complicated, but I have implemented a fix.

- The change affects **Department News index** pages and **Department profile index** pages.
- This is a *from-here-forward* change, so it won't take effect until these pages are published again. 
- It is backward compatible, so pages that have not been published since the change will not look weird or break.

1. I've moved dates from before the headline to after the headline. So users of assistive technology can scan the headlines and not skip over the article date.
2. I've changed headlines from `h3` to `h2` so the document outline is not broken (it was `h1.site-title` >  `h1.page-title` > `h3.article-title`). See attached image for more detail.
3. To improve usability, readability, and visual consistency, images float right instead of left.

1 and 2 are for users of assistive technology, 3 is for sighted users to more easily scan the page (and follows [news home page](http://news.ucsc.edu) convention).

![napkin 2 01-21-15 10 40 15 am](https://cloud.githubusercontent.com/assets/36719/5842465/e41ef094-a159-11e4-8b44-6181deb249fe.png)

**Comment by dajoturner** [comment]
@knice Did this go live in prod? There's a current ticket in ITRequest from Stephanie Sawyer, who says she just published the East Asian site news page, and was surprised to see all the images aligned right. See http://eastasianstudies.ucsc.edu/news-events/news/index.html, and see INC0225395. If it's from this, I'll tell her it's deliberate.

**Comment by thomasgardner** [comment]
I answered Stephanie's ITRequest ticket earlier today.
-Tom

On 1/21/15 2:52 PM, David Turner wrote:
>
> @knice <https://github.com/knice> Did this go live in prod? There's a 
> current ticket in ITRequest from Stephanie Sawyer, who says she just 
> published the East Asian site news page, and was surprised to see all 
> the images aligned right. See 
> http://eastasianstudies.ucsc.edu/news-events/news/index.html, and see 
> INC0225395. If it's from this, I'll tell her it's deliberate.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ucsc/webtemplates2014/issues/267#issuecomment-70938646>.
>

-- 

Tom Gardner | Academic Systems Group/Web Applications Team | UCSC | 
831-459-1719

**Comment by knice** [comment]
I just responded to Stephanie's ticket. This did go live in prod yesterday (after I tested in dev). Once I made the accessibility changes, it was obvious that the headlines were difficult to read at smaller screen sizes. So I flipped them to the right. I attached a couple of screen shots to the ticket, but here they are again.

### Images on the left (old)

![screen shot 2015-01-22 at 8 04 56 am](https://cloud.githubusercontent.com/assets/36719/5859303/45ca059a-a20e-11e4-834b-640fbae8168a.png)

### Images on the right (new)

![screen shot 2015-01-22 at 7 50 30 am](https://cloud.githubusercontent.com/assets/36719/5859320/5ae8c4ac-a20e-11e4-9fc7-321b64482eb4.png)

**Comment by teresasilva71** [comment]
Yeah, jus catching up on email and am just seeing this. I just opened
another issue for this. This is a big impact on me as I now have to update
all of my support/training materials with new screenshots. :(


On Thu, Jan 22, 2015 at 8:12 AM, Rob Knight <notifications@github.com>
wrote:

> I just responded to Stephanie's ticket. This did go live in prod yesterday
> (after I tested in dev). Once I made the accessibility changes, it was
> obvious that the headlines were difficult to read at smaller screen sizes.
> So I flipped them to the right. I attached a couple of screen shots to the
> ticket, but here they are again.
> Images on the left (old)
>
> [image: screen shot 2015-01-22 at 8 04 56 am]
> <https://cloud.githubusercontent.com/assets/36719/5859303/45ca059a-a20e-11e4-834b-640fbae8168a.png>
> Images on the right (new)
>
> [image: screen shot 2015-01-22 at 7 50 30 am]
> <https://cloud.githubusercontent.com/assets/36719/5859320/5ae8c4ac-a20e-11e4-9fc7-321b64482eb4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsc/webtemplates2014/issues/267#issuecomment-71045702>
> .
>



-- 

Teresa Silva
Campus WCMS TrainerCentral Web Migration LeadCampus WCMS Help
<http://wcmshelp.ucsc.edu/> ITS, UC Santa
Cruztasilva@ucsc.edu(831)459-1650
