### ISSUE TITLE
Google Search results not using proper headings for accessibility

### ISSUE THREAD

**Issue by dajoturner** [ucsc/webtemplates2014#276]
Len Burns issue. Sounds like we're not presenting our search results the way Google does on their own results. I'm marking this Fix Later and closing, since it is an enhancement.

Len's text:
There is no efficient way to located the results frame. There is a level one heading at the site search, but the results appear below this. Google itself places the results at a level 2 heading and each result at a level 3. This allows for efficient skimming for the desired entry.

Note: this was pulled out of #265.

**Comment by knice** [comment]
If I am understanding this correctly, the Google search results do not properly use headlines in their HTML markup. I've checked with the Google Custom Search Engine configuration and there is no way for us to change the HTML markup for search results supplied by Google.

@dajoturner, if I've properly characterized the issue raised by Len, we can close this because we can't do anything on our end to resolve it.

**Comment by dajoturner** [comment]
I think you have characterized it correctly, but I wish I understood better. When [talking about accessibility in their own search results](https://support.google.com/websearch/answer/181196?hl=en), Google says they're formatted exactly the way Len says. So is there a difference in how results are formatted when Search is embedded in a site? If so, why doesn't this come up as an issue when you Google it '<conspiracy>'.

I'm going to close this, and hope it doesn't pop up again at some point.

**Comment by knice** [comment]
You have it exactly right: there is a difference in how the results are formatted when embedded on a site. There are no headlines, everything is in table cells and styles are used to make the results look like headlines.

TBH, the headline is the only thing they do well for accessibility on their website; everything else is `<div>` soup.
