### ISSUE TITLE
Course schedule page alignment weirdness

### ISSUE THREAD

**Issue by dajoturner** [ucsc/webtemplates2014#315]
Looks like course and class pages are aligning all the way right, instead of having the standard padding. 
See: http://history.ucsc.edu/courses/class-schedule-view.php
Or:  http://education.ucsc.edu/courses/index.php
Or: http://psychology.ucsc.edu/courses/index.php

![image](https://cloud.githubusercontent.com/assets/8182013/4123089/ccd7b5f4-32ca-11e4-873c-4f163df4d5c7.png)

**Comment by teresasilva71** [comment]
Fiona noticed this again. It's getting noticed. We need to fix it.  Reopening. Sorry.

**Comment by knice** [comment]
OK, I've added a few lines of CSS that make for a reasonable fix in modern browsers. The table headers will not break to a second line in IE 10/11 and all the other browsers. There is no easy way to fix this in IE9 because the table isn't actually an HTML table.

@teresasilva71 Can you have Fiona take a look to verify everything looks OK for her? 

## IE 11 (smaller than desktop width)

![dnd](https://cloud.githubusercontent.com/assets/36719/7894632/3161f22a-0622-11e5-8ff8-6be4a9e8cb70.gif)
 
## IE 11 (desktop width)

![screen shot 2015-05-29 at 4 39 24 pm](https://cloud.githubusercontent.com/assets/36719/7894639/500d2ab4-0622-11e5-8d61-9167d31dcc08.png)

**Comment by knice** [comment]
Closing. Fiona has responded on the ITR ticket and this issue is resolved.

**Comment by luckyluke007** [comment]
Hello!

 

Important message, visit http://cilthastaligi.net/fact.php?hjvg

 

trung@scgstudio.com
